[package]
name = "dedelf"
version = "0.1.0"
authors = ["aclifford <alexandra.clifford@ll.mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#byteorder = "*"
#memmem = "*"
