[package]
name = "ded-elf"
version = "0.1.0"
authors = ["nand-nor <a13xandra.cliff0rd@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "*"
#memmem = "*"  may want to search for byte strings at some point
intervaltree = "0.2.5"

[[bin]]
name = "dedelf"
path = "src/bin/main.rs"